name: LevelSystem
api: 5.0.0
main: Laith98Dev\LevelSystem\Main
author: Laith98Dev, Convert to pm5 by Mrchlldev
website: https://github.com/Laith98Dev
version: 1.0.5+dev
description: Advanced LevelSystem for PocketMine-MP
depend: [PureChat, PurePerms, ScoreHud]

commands:
  ls:
    description: LevelSystem Command
    permission: levelsystem.command.staff

permissions:
  levelsystem.command.staff:
    default: op
